# Model arguments
model_name_or_path: ./output/llama-1b-bird-validator-fixer-fft/
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  ../data/llm_alignment/bird-p1-validator-fixer/dpo-llama-3-end2end-bird_train_fixed_sql: 1.0
  
dataset_splits:
- train_dpo
- test_dpo
preprocessing_num_workers: 12

# chat_template: "{{'<|start_header_id|>user<|end_header_id|>\n' + messages['prompt'] + '<|eot_id|>\n'}}{{'<|start_header_id|>assistant<|end_header_id|>\n' + messages['completion'] + '<|eot_id|>\n'}}"
report_to: ["tensorboard"]

# DPOTrainer arguments
bf16: true
beta: 100
do_eval: true
eval_strategy: "steps"
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 8.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: inverse_sqrt
max_length: 3300
max_prompt_length: 2000
num_train_epochs: 2
max_steps: 100000
optim: adamw_torch
output_dir: output/reproduce/orpo-llama-1b-validator-fixer-bird-beta0.5/
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_total_limit: 2
seed: 42
warmup_ratio: 0.01
