# Model arguments:
model_name_or_path: /home/datht/huggingface/meta-llama/Llama-3.2-1B-Instruct
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true
response_template: "<|start_header_id|>assistant<|end_header_id|>"

# Data training arguments
dataset_mixer:
  /home/datht/codes/data/multi-agents/validator/sft-validator_select_bird_with_evidence/: 1
  /home/datht/codes/data/multi-agents/validator/sft-validator_condition_bird_with_evidence/: 1
  /home/datht/codes/data/multi-agents/validator/sft-validator_join_bird_with_evidence/: 1
  # /home/datht/codes/data/multi-agents/validator/sft-validator_order_bird_with_evidence/: 1
dataset_splits:
- train
- test
preprocessing_num_workers: 24
chat_template: "{{'<|start_header_id|>user<|end_header_id|>\n' + messages['prompt'] + '<|eot_id|>\n'}}{{'<|start_header_id|>assistant<|end_header_id|>\n' + messages['completion'] + '<|eot_id|>\n'}}"

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: "no"
gradient_accumulation_steps: 32
gradient_checkpointing: true
hub_model_id: griffith-bigdata/llama-3b-bird-validator-fft
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 4
output_dir: output/llama-1b-bird-validator-fft
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: "epoch"
save_total_limit: 1
seed: 42